[package]
name = "vcnl4040_ex"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-hal = "1.0.0-alpha.10"
i2cdev = "0.6.1"
simple_logger = "1.13.0"
log = "0.4.14"
tokio = {version="1.12.0", features = ["full"]}
vncnl4040 = { path = "../.." }
